vim.opt.tabstop = 4
vim.opt.expandtab = true
vim.opt.switchbuf = 'useopen'
vim.opt.shiftwidth = 4
vim.opt.wrap = false
vim.opt.signcolumn = 'yes:1'
vim.opt.smartindent = true
vim.opt.showcmd = true
vim.opt.smartcase = true
vim.opt.showmatch = false
vim.opt.showtabline = 1
vim.opt.helplang = 'ja', 'en'
vim.opt.clipboard = 'unnamedplus'
vim.opt.number = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.lazyredraw = true
vim.opt.ttyfast = true
vim.opt.list = true
vim.opt.listchars = "tab:  ,extends: ,precedes: ,nbsp: ,eol: ,trail:."
vim.opt.hlsearch = true
